Monitor job runs
ctsit/redcapcustodian pull request #165
Opened 2024-09-13 22:09 UTC by ljwoodley

Possible solution to issue #100?

2024-09-30 20:45 UTC, pbchase requested changes
This is super simple and it _works_. We could use it as-is, but I'd like to see two more features. Could you add these?

1. Add the ability to pass optional arguments to an etl.
2. implement the same functionality in the existing [render_report.R](https://github.com/ctsit/redcapcustodian/blob/master/report/render_report.R) and its copy in the [study_template](https://github.com/ctsit/redcapcustodian/tree/master/study_template/report)

2024-09-30 20:45 UTC, pbchase commented on etl/run_etl.R
> +parser$add_argument("script_name", nargs=1, help="Script to be run")
Could you allow for optional parameters? it's quite rare but we do pass an argument to one of out ETLs in the rcc.ctsit repo

2024-09-30 20:45 UTC, pbchase commented on etl/run_etl.R
> +  rscript(script_name, stderr = "log.txt")
...and then use the arguments here?

2024-10-14 18:19 UTC, pbchase commented
Here's some example code I wrote to test a different way of specifying the optional arguments to the script called by `run_etl.R`

```r
library(argparse)

parser <- ArgumentParser()

parser$add_argument("file", nargs = 1, help = "RScript to be run")
parser$add_argument("optional_args", nargs='+', help = "optional arguments to the script to be run")

args <- parser$parse_args()

paste0("The first argument, file, has a value of '", args$file, "'")
paste0("The optional arguments that follow are '", paste(args$optional_args, collapse = " "), "'")
```

Could you revise `run_etl.R` to use use this model for optional arguments?

2024-10-14 21:21 UTC, ljwoodley commented
> Here's some example code I wrote to test a different way of specifying the optional arguments to the script called by `run_etl.R`
> 
> ```r
> library(argparse)
> 
> parser <- ArgumentParser()
> 
> parser$add_argument("file", nargs = 1, help = "RScript to be run")
> parser$add_argument("optional_args", nargs='+', help = "optional arguments to the script to be run")
> 
> args <- parser$parse_args()
> 
> paste0("The first argument, file, has a value of '", args$file, "'")
> paste0("The optional arguments that follow are '", paste(args$optional_args, collapse = " "), "'")
> ```
> 
> Could you revise `run_etl.R` to use use this model for optional arguments?

I don't understand this change?

`parser$add_argument("optional_args", nargs='+', help = "optional arguments to the script to be run")` does not allow for an optional argumnet as it requires at least one value when the script runs due to `nargs='+`'.

`Rscript etl/run_etl.R etl/test_failure_alert.R` fails with this error
 
![Screenshot 2024-10-14 at 5 16 06 PM](https://github.com/user-attachments/assets/0f0dba7d-fb37-4eef-b4bd-ae6bbd30597b)


Also, `Rscript etl/run_etl.R etl/test_failure_alert.R arg1 arg2` is not parsing the arguments properly.

![Screenshot 2024-10-14 at 5 17 07 PM](https://github.com/user-attachments/assets/e71fb3e3-d83b-4041-8457-2453fe440b84)

@pbchase

2024-10-15 17:49 UTC, pbchase requested changes
I made some suggestions.

We'll make changes to `render_report.R` later after the rcc.grace PR is finished.

2024-10-16 20:21 UTC, pbchase approved these changes

2024-10-16 20:21 UTC, merged