Improve logging in project deletes
ctsit/redcapcustodian pull request #171
Opened 2024-12-02 15:13 UTC by saipavan10-git

This pull request includes significant changes to the `delete_project` function and its associated tests. The changes enhance logging, and update the test cases to reflect the new logging structure. Addresses #169 

## Enhancements to `delete_project` function:

* Enhanced logging by adding detailed log parameters such as `ts`, `user`, `ip`, `page`, `event`, `object_type`, `sql_log`, `pk`, `event_id`, `data_values`, `description`, `legacy`, and `change_reason`.

2024-12-03 12:42 UTC, pbchase requested changes
See comments

2024-12-03 12:42 UTC, pbchase commented on R/delete_project.R
> +    user <- "admin" # Placeholder for user
Test this with an invalid username to see how REDCap's UI will behave.

Then, revise the code to default it first to, the value in sys.getenv("API_USER"), then--if invalid usernames are allowed--the script name.

2024-12-03 12:42 UTC, pbchase commented on R/delete_project.R
> +    ip <- "192.168.65.1" # Placeholder for IP address
Use getip::getip("local") to get the local IP address. Make getip a required package for redcapcustodian.

2024-12-05 13:55 UTC, pbchase commented
@saipavan10-git, note that the checks are failing. If you drill in on that error you will see the error is pretty obvious: redcapcustodian now needs `getip` and the container used by the github action does not have that. I've fixed these before, but I should hand this one to you. I'll show you path, so you can fix it. 

Could you document this procedure in addition to fixing it? The procedure doesn't seem clear unless you've already set up GitHub actions to perform automated testing. Any thoughts on where to put this procedure? Could we add a vignette for developers?

You can see the configuration for the action that failed at [run-tests.yaml](https://github.com/ctsit/redcapcustodian/blob/master/.github/workflows/run-tests.yaml). It uses an image at [ghcr.io/ctsit/rstudio-ci](ghcr.io/ctsit/rstudio-ci). The Dockerfile that defines that is at [Dockerfile](https://github.com/ctsit/rstudio-dockerfile/blob/master/Dockerfile). Historically, we have added required packages in this Dockerfile. That should work quickly and easily, but I think you can install packages in `run-tests.yaml` that might be a better  way to make the package self-documenting, but that might also make tests slower to run.

2024-12-05 17:50 UTC, saipavan10-git commented
I updated this [dockerfile](https://github.com/ctsit/redcapcustodian/blob/da6185fdb37bcece14e1dba7df1863665bd78e80/Dockerfile) thinking this will fix the issue.

Adding a guide vignette for developers is a great idea. I can create one to document the fix for this issue. If we add new dependencies more frequently, we could add a step to setup dependencies in run-tests.yaml like in [pkgdown.yaml](https://github.com/ctsit/redcapcustodian/blob/da6185fdb37bcece14e1dba7df1863665bd78e80/.github/workflows/pkgdown.yaml#L31-L34). This will reduce the need to update the [rstudio-Dockerfile](https://github.com/ctsit/rstudio-dockerfile/blob/master/Dockerfile). Also, setup r dependencies has an option to [cache](https://arc.net/l/quote/xuqtunbp) the packages that might help with the speed of the gh action.

2024-12-05 18:39 UTC, pbchase commented
> I updated this [dockerfile](https://github.com/ctsit/redcapcustodian/blob/da6185fdb37bcece14e1dba7df1863665bd78e80/Dockerfile) thinking this will fix the issue.

That's necessary, but not sufficient to make CI-tests work

> Adding a guide vignette for developers is a great idea. I can create one to document the fix for this issue. If we add new dependencies more frequently, we could add a step to setup dependencies in run-tests.yaml like in [pkgdown.yaml](https://github.com/ctsit/redcapcustodian/blob/da6185fdb37bcece14e1dba7df1863665bd78e80/.github/workflows/pkgdown.yaml#L31-L34). This will reduce the need to update the [rstudio-Dockerfile](https://github.com/ctsit/rstudio-dockerfile/blob/master/Dockerfile). 

Right! I knew we had done this before, but I couldn't locate it.

> Also, setup r dependencies has an option to [cache](https://arc.net/l/quote/xuqtunbp) the packages that might help with the speed of the gh action.

That minimizes the downside of the more local management of dependencies.  I like it :-)

2024-12-06 16:18 UTC, pbchase approved these changes

2024-12-06 16:18 UTC, merged